defaults:
  - default
  - env: local
  - _self_

model:
  name: upsample_cnn
  params:
    _target_: superresolution.models.upsample_cnn.SuperResolutionUpsampleCNN
    hidden_channels: 32
    num_blocks: 4
    num_upsample_stages: 2  # 2 stages of 2x: 32->64->128. Must match downsample_step (128/4=32).
